name: image_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7
  path_provider: ^2.0.14
  video_player: ^2.6.0
  chewie: ^1.4.0
  permission_handler: ^10.2.0
  file_picker: ^5.2.6
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_easyloading: ^3.0.5
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  cached_network_image: ^3.2.3
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.4.0
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_local_notifications: ^13.0.0
  cloud_firestore: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
